# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-31 07:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MagicLinkCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Magic Link Credentials',
                'ordering': ('-created_at',),
                'get_latest_by': 'created_at',
            },
        ),
        migrations.AlterUniqueTogether(
            name='magiclinkcredential',
            unique_together=set([('key', 'user', 'is_active')]),
        ),
    ]
